### ISSUE TITLE
gVisor cannot run ubuntu container

### ISSUE THREAD

**Issue by geloizi** [google/gvisor#72]
[runsc.log.20180618-010719.846873.create.txt](https://github.com/google/gvisor/files/2109642/runsc.log.20180618-010719.846873.create.txt)
[runsc.log.20180618-010719.851934.boot.txt](https://github.com/google/gvisor/files/2109643/runsc.log.20180618-010719.851934.boot.txt)
[runsc.log.20180618-010719.855993.gofer.txt](https://github.com/google/gvisor/files/2109644/runsc.log.20180618-010719.855993.gofer.txt)
[runsc.log.20180618-010719.860303.gofer.txt](https://github.com/google/gvisor/files/2109645/runsc.log.20180618-010719.860303.gofer.txt)

I've tried to run several containers with gVisor. `hello-world` works fine, but `ubuntu` doesn't. It completely freezes  the terminal. `docker ps` produces an empty list. Without `--runtime=runsc` option `ubuntu` container starts as expected. 

Command:

```
docker run --runtime=runsc -it ubuntu /bin/bash  
```

```
docker version                                                                                                                                                      
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

```
uname -a
Linux dev 4.9.93-boot2docker #1 SMP Thu May 10 16:27:54 UTC 2018 x86_64 GNU/Linux
```

**Comment by dgageot** [comment]
Same here

**Comment by ydjainopensource** [comment]
I am able to reproduce this issue. 
#67 #72 #73 #74 may all be caused due to the same underlying issue.
A prior build of runsc runs fine. Looks like a new commit introduced this in the latest build. 

I am new here. Can someone from the runsc team confirm?

**Comment by geloizi** [comment]
I tried to build `runsc` from older sources (June 1). It works.

**Comment by fvoznika** [comment]
This was a regression added on Friday. Please check that d509d6c fixed it. Sorry for the trouble.

**Comment by geloizi** [comment]
confirmed. The issue has been fixed. Thanks!

**Comment by tianburg** [comment]
thanks ,  @fvoznika    @geloizi 

you mentioned that :  d509d6c fixed it . 
how can I sync my local copy code with  d509d6c commit ?
I git pull and sync my code with master branch , but the error still exist here .

Thanks for borther

**Comment by ydjainopensource** [comment]
@tianburg after you pull you need to rebuild the project, copy the compiled binary and then restart docker. See the readme for details.

**Comment by tianburg** [comment]
@ydjainopensource   

I do what ReadMe listed steps again , but the error still there .

below is my runsc version info : 

> $ runsc version
> I0619 16:50:39.650078   15921 x:0] ***************************
> I0619 16:50:39.650153   15921 x:0] Args: [runsc version]
> I0619 16:50:39.650170   15921 x:0] Git Revision: 873ec0c414973e829c1570f21d0d2e2a0df681f4
> I0619 16:50:39.650179   15921 x:0] PID: 15921
> I0619 16:50:39.650188   15921 x:0] UID: 1000, GID: 1000
> I0619 16:50:39.650194   15921 x:0] Configuration:
> I0619 16:50:39.650200   15921 x:0] 		RootDir: /run/user/1000/runsc
> I0619 16:50:39.650246   15921 x:0] 		Platform: ptrace
> I0619 16:50:39.650269   15921 x:0] 		FileAccess: proxy, overlay: false
> I0619 16:50:39.650283   15921 x:0] 		Network: sandbox, logging: false
> I0619 16:50:39.650297   15921 x:0] 		Strace: false, max size: 1024, syscalls: []
> I0619 16:50:39.650307   15921 x:0] ***************************
>

**Comment by ydjainopensource** [comment]
@fvoznika I tried compiling with the latest commit. Although most of the times the container runs properly, I am experiencing container crashes randomly. This is the log generated

> D0619 14:03:27.215219    7310 x:0] Connecting to sandbox "257a1ca8fe390543336e75205f47b8645a37c83f873dd832b95833d7e9aeca34"
> W0619 14:03:27.215297    7310 x:0] FATAL ERROR: error connecting to control server at pid 7183: connection refused

I would like to look into this issue. However, since I am new to the code base can you help me get started?

@tianburg Please send a copy of the [logs](https://github.com/google/gvisor#debugging). I have the same runsc version as yours are you experiencing similar behavior?

**Comment by tianburg** [comment]
hi team,

I attached my log files. ( by rename them with a .txt for upload )


[runsc.log.20180620-062414.616856.gofer.txt](https://github.com/google/gvisor/files/2117141/runsc.log.20180620-062414.616856.gofer.txt)
[runsc.log.20180620-062414.604577.gofer.txt](https://github.com/google/gvisor/files/2117142/runsc.log.20180620-062414.604577.gofer.txt)
[runsc.log.20180620-062414.590591.create.txt](https://github.com/google/gvisor/files/2117143/runsc.log.20180620-062414.590591.create.txt)

**Comment by fvoznika** [comment]
`runsc create` starts up 2 children processes to run the sandbox. First it starts `runsc gofer` which acts as a file proxy. Then it starts `runsc boot` which is the sandbox itself. Other commands, like `runsc start` or `runsc ps` communicate with the sandbox process via a unix socket. So when you see connection errors, it normally means that the sandbox process has exited. Log files `*.boot` contain the logs for the sandbox process and may tell you what happened. In case the sandbox hit a panic, `docker logs` will normally show the stack trace that caused the crash.

@tianburg, are these all logs you have? If yes, `runsc boot` could be failing to access the log directory (/tmp/runsc). In `*.create.txt`, I can see that `runsc boot` started with PID: 20435, but the fact that there is no log file tells me that it failed very early on. Log file creation is one of the first thing it does.
